version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/n8n-nodes-gigstack/dist
      - ./package.json:/home/node/.n8n/custom/node_modules/n8n-nodes-gigstack/package.json

volumes:
  n8n_data:
